"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Copy, Download, CheckCircle2, Shield, Terminal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export default function ProofPage() {
  const [copied, setCopied] = useState(false);
  const [jsonString, setJsonString] = useState<string>("Loading proof...");

  // Load the REAL signed proof generated by the agent from on-chain state
  useEffect(() => {
    fetch("/franchisa_proof_NVDA.json")
      .then((r) => r.json())
      .then((data) => setJsonString(JSON.stringify(data, null, 2)))
      .catch(() => setJsonString("Failed to load proof file."));
  }, []);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(jsonString);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([jsonString], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "franchisa_proof_NVDA.json";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-3xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="mb-10"
      >
        <p className="text-sm text-muted-foreground mb-2">Export</p>
        <h1 className="text-3xl md:text-4xl font-semibold tracking-tight mb-3">
          Governance Proof
        </h1>
        <p className="text-muted-foreground text-[15px] leading-relaxed max-w-lg">
          Cryptographically signed vote results, packaged for custodian
          ingestion. Tamper-proof, sourced directly from on-chain state.
        </p>
      </motion.div>

      {/* How it works */}
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.05 }}
        className="rounded-2xl border border-border dark:border-white/10 bg-card/80 dark:bg-white/[0.03] p-6 mb-6"
      >
        <div className="flex items-center gap-2 mb-4">
          <Shield className="h-4 w-4 text-primary" />
          <p className="text-sm font-medium text-foreground/80">
            How Governance Proofs Work
          </p>
        </div>
        <div className="space-y-3 text-sm text-muted-foreground">
          <p>
            After votes are cast on-chain, the AI agent generates a signed proof
            that attests the entire pipeline — from SEC filing to on-chain vote
            to final result.
          </p>
          <div className="flex items-start gap-3 p-3 rounded-lg bg-muted/30 dark:bg-white/[0.02] border border-border/50 dark:border-white/5">
            <Terminal className="h-4 w-4 mt-0.5 shrink-0 text-muted-foreground/60" />
            <div className="font-mono text-xs space-y-1">
              <p className="text-foreground/70">
                # Generate a proof via the CLI agent
              </p>
              <p>
                python agent.py proof --ticker NVDA
              </p>
              <p className="text-foreground/70 mt-2">
                # Verify this proof yourself (signature + signer recovery)
              </p>
              <p>
                python agent.py verify franchisa_proof_NVDA.json
              </p>
            </div>
          </div>
          <p className="text-xs text-muted-foreground/60">
            The proof below is REAL: generated by the agent from on-chain state
            for NVIDIA&apos;s 2026 annual meeting, ECDSA-signed, and carrying
            the keccak256 hash of the actual SEC DEF 14A filing — anyone can
            re-fetch the filing by accession number and verify the hash.
          </p>
        </div>
      </motion.div>

      {/* Proof JSON */}
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.1 }}
        className="rounded-2xl border border-border dark:border-white/10 bg-card dark:bg-white/[0.03] backdrop-blur-sm overflow-hidden mb-6"
      >
        <div className="flex items-center justify-between px-5 py-3 border-b border-border dark:border-white/10">
          <div className="flex items-center gap-2">
            <span className="text-sm font-medium font-mono text-foreground/70">
              franchisa_proof_NVDA.json
            </span>
            <Badge className="text-[10px] rounded-full bg-emerald-500/10 text-emerald-400 border-emerald-500/20 hover:bg-emerald-500/10">
              Real Signed Proof
            </Badge>
          </div>
          <div className="flex items-center gap-1">
            <Button
              size="sm"
              variant="ghost"
              onClick={handleCopy}
              className="text-xs h-7 cursor-pointer text-muted-foreground hover:text-foreground"
            >
              {copied ? (
                <>
                  <CheckCircle2 className="h-3 w-3 mr-1" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="h-3 w-3 mr-1" />
                  Copy
                </>
              )}
            </Button>
            <Button
              size="sm"
              variant="ghost"
              onClick={handleDownload}
              className="text-xs h-7 cursor-pointer text-muted-foreground hover:text-foreground"
            >
              <Download className="h-3 w-3 mr-1" />
              Download
            </Button>
          </div>
        </div>
        <pre className="p-5 text-xs leading-relaxed overflow-x-auto text-muted-foreground font-mono">
          <code>{jsonString}</code>
        </pre>
      </motion.div>

      <motion.p
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.3, delay: 0.2 }}
        className="text-xs text-muted-foreground/50 leading-relaxed"
      >
        See{" "}
        <a
          href="https://github.com/Savage27z/Franchisa/blob/main/PROOF_SPEC.md"
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary/60 hover:text-primary transition-colors"
        >
          PROOF_SPEC.md
        </a>{" "}
        for the full v1 specification including ECDSA signature construction,
        verification flow, and agent trace format.
      </motion.p>
    </div>
  );
}
